### PR TITLE
Add whitelisted channel logic

### PR DESCRIPTION
**Pull request by AshesOfOwls**
Add whitelisted channel logic

### CODE REVIEW

**Comment by AshesOfOwls** [comment]
Whoops sorry

**Comment by calzoneman** [comment]
Regardless of the mistaken PR, I'll go ahead and point out that this is likely not the file you actually want to update (unless you are using the multi-server support, which is undocumented and pretty much no one outside of the cytu.be server would need to use it anyways).

You probably meant to update the [local channel index](https://github.com/calzoneman/sync/blob/3.0/src/web/localchannelindex.js) instead.

**Comment by calzoneman** [comment]
Although, if you were the person messaging me about how to keep channels loaded even if they have 0 viewers, you probably don't need to muck with the public index code, you can just remove [this](https://github.com/calzoneman/sync/blob/3.0/src/server.js#L295-L297) instead so that channels are never unloaded from memory (the channel index only shows those channels which are "loaded").

**Comment by AshesOfOwls** [comment]
@calzoneman That was my buddy I am working on it with. Thank you for the insight we are gonna try to implement that now

**Pull request closed without merging**
