### PR TITLE
Add some various harmless tags to the XSS whitelist

### LINKED ISSUE #579: Allow sup and sub tags
Change the tag filter to allow the `<sup>` and `<sub>` elements for formatting text.

### PR DESCRIPTION
**Pull request by Xaekai**
sub, sup: Closes #579
cite, small: Bootstrap uses these for blockquotes
template: Will allow for cleaner channel scripts. Since it's contents are inert it will also allow channel admins to have "comments" in their banner.

### CODE REVIEW

**Comment by calzoneman** [comment]
Lel wut, why is this merge confli- oh because you changed the version number.

**Comment by Xaekai** [comment]
Do I need to take some sort of action? I didn't realize it would create a conflict since I presumed the PR's would be pulled in chronological order, and only the version line was changed.

**Comment by calzoneman** [comment]
So even if they are pulled in order, since the same line was changed in order and they aren't rebased between merges, it requires manual effort to merge.  I'll probably just use the github-provided commands to manually merge and fix the conflicts.

**Comment by Xaekai** [comment]
There.

**Pull request merged**
