### PR TITLE
Fix max duration input bug

### PR DESCRIPTION
**Pull request by deerfarce**
lazily cast rawMax to string before processing it.

### CODE REVIEW

**Comment by Xaekai** [comment]
Do not be lazy with code in the server core

:angry:

**Comment by deerfarce** [comment]
Improved it I think, works just fine.

**Comment by calzoneman** [comment]
What bug is being fixed here exactly?  The option should accept exactly either a string or a number, not both.  So if the client is already parsing the timestring and sending the raw number, then the server should accept a number only.

**Comment by Xaekai** [comment]
There is actually a bug somewhere, but I haven't had a chance to look for it myself, and have no idea if this PR actually fixes anything
image

**Comment by deerfarce** [comment]
In Channel Settings, putting something in such as 00:00:59 will cause an error with the message, "Input must be a time in the format HH:MM:SS, not 59." The server receives a number, not a string, so it just passes right into the first if block and emits the validationError.

**Comment by calzoneman** [comment]
I could have sworn I tested this before checking it in, but oh well.  It looks like indeed the UI converts the HH:MM:SS timestamp into a number before passing it to the server.  So I guess the parsing logic can be removed and just accept a number.  Easy fix.

**Comment by calzoneman** [comment]
Fixed via https://github.com/calzoneman/sync/commit/55b03d51d70dd44bd756b67c516ee6d0f8431977

**Pull request closed without merging**
