### PR TITLE
Add support to Violentmonkey

### PR DESCRIPTION
**Pull request by KingThunder**
Change based on #713

### CODE REVIEW

**Comment by Xaekai** [comment]
LGTM.

**Comment by calzoneman** [comment]
Should we bump the version number like in https://github.com/calzoneman/sync/commit/85169fbb5678579fdf44018cc4a50ca845c0459f so that ViolentMonkey users who have already installed the script will be prompted to upgrade it?

**Comment by calzoneman** [comment]
Should be resolved by https://github.com/calzoneman/sync/commit/342e5d406a60914a94037a78051ba480c191aed4.

I don't have Violentmonkey, can someone test on https://beta.synchtube.me?

**Comment by KingThunder** [comment]
Tested https://beta.synchtube.me and it works!

**Pull request closed without merging**
