### PR TITLE
HTTPS enforcement phase 1

### PR DESCRIPTION
**Pull request by calzoneman**
Phase 1 of HTTPS enforcement:

  * All new external CSS links must be HTTPS
  * All new external JS links must be HTTPS
  * All new profile image links must be HTTPS
  * Existing HTTP links remain untouched

This needs some testing in beta, haven't deployed it yet.

During Phase 2, existing HTTP links will be phased out by prompting users to change them (with a warning for the cutoff date).  Phase 3 actually enforces HTTPS by invalidating all non-HTTPS links for these 3 components.

Warning/enforcement of raw video links will be handled in a different commit.  Emotes/inline images will be handled separately (I haven't decided how yet).

### CODE REVIEW

**Comment by Xaekai** [comment]
I think enforcing https on the channels dynamic inline content would be impractical. Everything else seems perfectly reasonable.

**Comment by calzoneman** [comment]
Change is live on beta.

**Comment by irufus** [comment]
I saw this in action on v4c. Any reason why you're not force upgrading the client on access?

**Comment by calzoneman** [comment]
>I saw this in action on v4c

Sorry for the confusion, I meant to write up some documentation/FAQ but the announcement went up prematurely.

>Any reason why you're not force upgrading the client on access?

This change is referring specifically to *external* links to CSS/JS.  Inline CSS/JS will continue to be served via the CyTube socket, and will not require any changes from channel owners.

The end goal is for all access to CyTube to be enforced over HTTPS via the `Strict-Transport-Security` header, which directs users' browsers to use https://cytu.be.  However, browser security policy prohibits loading active content (such as CSS/JS) from a plain HTTP URL when the page itself is HTTPS.  Hence, channels' external content will need to be migrated first, otherwise it will stop working once CyTube goes mandatory HTTPS.

The information/FAQ I post later might answer any more questions you have.

**Comment by calzoneman** [comment]
http://blog.cytu.be/2016-12-19-https.html

**Comment by SysadminJeroen** [comment]
One thing that I'm recommending to enforce HTTPS is when someone includes an image from a site that does not support HTTPS as an emoticon, CyTube should use https://github.com/atmos/camo on a subdomain and pass the images through the proxy. The proxy will anonymize the traffic and it'll prevent mixed content warnings. GitHub is using Camo for mixed content as well and I have been using it on a phpBB installation and it just works.

**Comment by calzoneman** [comment]
That is an interesting idea that I'll have to look into, so thanks for sharing.  I've always liked the idea of proxying user avatars and chat emotes, but I've always been concerned about (1) potential bandwidth costs, and (2) people abusing it to host illegal content.

**Comment by SysadminJeroen** [comment]
All it does is proxy the content through a webserver that actually does use HTTPS. So no illegal content emails due to no content actually getting hosted on the server. I mean they don't send an email to all the Tier 1 providers just because they transferred the illegal content from one provider through their network to another provider.


And the amount of bandwidth depends.
Some browsers cache images.
I don't really have anything else to say, as I do not know how much bandwidth CyTube will use nor how much bandwith CyTube has.

**Pull request merged**
